all:
	g++ Output_2_Byte.cpp -o length_2
	g++ Output_4_Byte.cpp -o length_4
	g++ Output_8_Byte.cpp -o length_8
	g++ Output_32_Byte.cpp -o length_32
	g++ Output_128_Byte.cpp -o length_128
	g++ Output_1024_Byte.cpp -o length_1024
